### ISSUE TITLE
ECDH generates a private key with only 8 bit of length

### ISSUE THREAD

**Issue by liiir1985** [MidLevel/MLAPI.Cryptography#2]
The ECDH implementation of this library generates a private key with only 8 bit of length. this makes the library not secure at all. It can only generate 256 different key pairs which can be cracked in miliseconds

**Comment by TwoTenPvP** [comment]
> The ECDH implementation of this library generates a private key with only 8 bit of length. this makes the library not secure at all. It can only generate 256 different key pairs which can be cracked in miliseconds

Which keys? The ECDH private key is not 8 bits.

**Comment by liiir1985** [comment]
But in the fact it is 8 bits, the value of ecdh.priv is always between 0 and 255, it used order.DataLength to generate the random bits, which is 8
